### ISSUE TITLE
Ability to add multiple properties of same value within a single driver

### ISSUE THREAD

**Issue by trevasco** [the-illarionov/the-supersonic-plugin-for-scroll-based-animation#1]
Trying to do something like the below example, where one driver can control multiple elements that are translating different values, but doesn't seem like that is possible currently, and it only adds the transforms to the last element. Is there a way to do something like this without having to make an entirely new driver for every element, or am I missing something?

```
drivers: {
  "driver-name": {
    properties: {
      translateX: {
        start: 0,
        end: 100,
        unit: "px",
        elements: [ ".element-1" ],
      },
      translateX: {
        start: 0,
        end: 200,
        unit: "px",
        elements: [ ".element-2" ],
      },
      translateX: {
        start: 0,
        end: 300,
        unit: "px",
        elements: [ ".element-3" ],
      },
    },
  },
}
```

**Comment by the-illarionov** [comment]
Yes, here is an [example](https://the-illarionov.github.io/the-supersonic-plugin-for-scroll-based-animation/#multiple-elements) of what you want to do.

Short said, you can make it like this:
```javascript
drivers: {
  "driver-name": {
    properties: {
      translateX: {
        start: 0,
        end: 100,
        unit: "px",
        elements: [ ".element-1", ".element-2", ".element-3" ],
      },
    },
  },
}
```

**Comment by trevasco** [comment]
@the-illarionov sorry, that's not what I described. In my example each element gets a different px value, not all the same 100px like you have.

**Comment by the-illarionov** [comment]
@trevasco uh, my bad, sorry. Yes, you have to use different drivers for each "translateX", it is a price for flexibility.

However, you can still stand with one driver and get different results with [that trick](https://the-illarionov.github.io/the-supersonic-plugin-for-scroll-based-animation/#custom-easing), but it will be much simplier if you will just stick to separate drivers.
